# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Questionare.Question')),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionare.Person'),
        ),
    ]
